name = "argus"
description = "Argon2 password hashing library for Gleam, based on the reference C implementation."
docs_url = "https://hexdocs.pm/argus/"
repo_url = "https://github.com/Pevensie/argus"
category = ""
