name = "ask"
description = "Functional utilities for building custom predicates, orderings, and equivalences"
docs_url = "https://hexdocs.pm/ask/"
repo_url = "https://github.com/furrycatherder/gleam-ask"
category = ""
