name = "crabbucket_redis"
description = "Gleam + Redis token bucket rate limiting library"
docs_url = "https://hexdocs.pm/crabbucket_redis/"
repo_url = "https://github.com/skinkade/crabbucket_redis"
category = ""
