name = "crabbucket_pgo"
description = "Gleam + Postgres token bucket rate limiting library"
docs_url = "https://hexdocs.pm/crabbucket_pgo/"
repo_url = "https://github.com/skinkade/crabbucket_pgo"
category = ""
