name = "gleamsver"
description = "Comprehensive set of native Gleam utilities for handling SemVer 2.0.0 version strings."
docs_url = "https://hexdocs.pm/gleamsver/"
repo_url = "https://github.com/aznashwan/gleamsver"
category = "Parsing"
