name = "glebs"
description = "An OAuth PKCE helper for Gleam in Browser. You can easily use this with lustre."
docs_url = "https://hexdocs.pm/glebs/"
repo_url = "https://github.com/andho/glebs"
category = ""
