name = "glency"
description = "Tiny Gleam dependency injection. Make IO functions unit tests friendly."
docs_url = "https://hexdocs.pm/glency/"
repo_url = "https://github.com/darky/glency"
category = ""
