name = "gxyz"
description = "🛒 A small library of helper functions, that works as a companion of gleam_stdlib"
docs_url = "https://hexdocs.pm/gxyz/"
repo_url = "https://github.com/bwireman/gxyz"
category = ""
