name = "lustre_transition"
description = "Transitions for lustre, designed for use with Tailwind"
docs_url = "https://hexdocs.pm/lustre_transition/"
repo_url = "https://github.com/codemonkey76/lustre_transition"
category = ""
