name = "lustre_hash_state"
description = "lustre effects for maintaining application state in the hash fragment"
docs_url = "https://hexdocs.pm/lustre_hash_state/"
repo_url = "https://github.com/jshawl/lustre_hash_state"
category = ""
