name = "meadow"
description = "A server side for glare, the web framework based on SolidJS, adding server signals and more."
docs_url = "https://hexdocs.pm/meadow/"
repo_url = "https://github.com/JoelVerm/meadow"
category = ""
