name = "melon"
description = "A Gleam library for running containers tailored to testing purposes."
docs_url = "https://hexdocs.pm/melon/"
repo_url = "https://github.com/patrik-kuehl/melon"
category = ""
