name = "priorityq"
description = "A priority queue implementation based on max pairing heaps. Written in pure Gleam."
docs_url = "https://hexdocs.pm/priorityq/"
repo_url = "https://github.com/nicklimmm/priorityq"
category = ""
