name = "radish_fork"
description = "A Gleam client for Valkey, KeyDB, Redis and other tools with compatible APIs"
docs_url = "https://hexdocs.pm/radish_fork/"
repo_url = "https://github.com/rojnwa/radish"
category = ""
