name = "stacky"
description = "BEAM stack trace in Gleam: a stack trace of stack frames with module name, function name, arity, file name and line number."
docs_url = "https://hexdocs.pm/stacky/"
repo_url = "https://github.com/inoas/stacky"
category = ""
