name = "staff_ai"
description = "Become the CEO of your own AI workforce, efficiently managing countless intelligent agents with minimal resources."
docs_url = "https://hexdocs.pm/staff_ai/"
repo_url = "https://github.com/chainyo/staff-ai"
category = ""
