name = "tulip"
description = "Tulip is a simple Gleam project for adding color to your terminal output. All 256 ANSI colors are supported."
docs_url = "https://hexdocs.pm/tulip/"
repo_url = "https://github.com/johnnymayodev/tulip"
category = ""
