name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: erlef/setup-beam@ee09b1e59bb240681c382eb1f0abc6a04af72764 # v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.1.0"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
      - run: gleam run check
